<?php
$lang = array(
'postinstall' => 'Post Install Message.',
'postuninstall' => '',
'really_uninstall' => 'Really? Are you sure
you want to unsinstall this fine module?',
'uninstalled' => 'Module Uninstalled.',
'installed' => 'Module version %s installed.',
'upgraded' => 'Module upgraded to version %s.',
'moddescription' => 'This module is generated by M&C Factory',

'tab_items' => 'Items',
'tab_templates' => 'Templates',
'tab_options' => 'Options',
'tab_help' => 'Help',

'error' => 'Error!',
'admin_title' => '{{$module->getModuleName()}} Admin Panel',
'admindescription' => 'This module helps you to manage specific items',
'titleTemplate' => 'Title',
'codeTemplate' => 'Template',
'accessdenied' => 'Access Denied. Please check your permissions.',
'postinstall' => 'Be sure to set "Manage {{$module->getModuleName()}}" permissions to use this module!',

'submit' => 'Submit',
'apply' => 'Apply',
'cancel' => 'Cancel',
'restorelist' => 'Restore list',
'restoredetails' => 'Restore details',
'publish' => 'Publish',
'unpublish' => 'Unpublish',


'add template' => 'Add template',
'select one' => 'Select one',
'form_template' => 'Template',
'form_restore_template_from' => 'Restore template from',
'form_code' => 'Code',
'form_default_template_for' => 'Default template for',
'default template for' => 'default template for "%s" action',

// user form
'you do not have the permission to use this action' => 'You do not have the permission to use this action',
'form_user_id' => 'User id',
'form_title' => 'Title',
'item posted' => 'Item successfully posted',

'save' => 'Save',
'save_add' => 'Save &amp; add a new item',
'save_continue' => 'Save & continue editing',
'delete' => 'Delete',
'add_item' => 'Add item',
'add_item_for' => 'Add item for [%s]',
'edit_item' => 'Edit item',
'update_objects' => 'Update objects',
'preview_s' => 'Preview [%s]',

'form_parent_id' => 'Parent',
'form_order_by' => 'Order by',
'form_order_by_direction' => 'Order direction',
'form_items_per_page' => 'Items per page',
'form_date_format' => 'Date format',
'form_default_page' => 'Default page',
'form_show_parent' => 'Show parents dropdown',
'form_show_parent_first_level' => 'Show parents first level only',
'form_save_add' => 'Show Save &amp; add button',
'form_index_content' => 'Index content',
'form_use_cmon' => 'Use Campaign Monitor',
'form_cmon_from' => 'Campaign Monitor From',
'form_cmon_from_email' => 'Campaign Monitor From email',
'form_cmon_template' => 'Campaign Monitor template',
'form_cmon_template_plain' => 'Campaign Monitor template (plain text version)',
'form_cmon_default_page' => 'Default page for Campaign Monitor HTML',
'form_use_twitter' => 'Use Twitter',
'form_twitter_template' => 'Twitter template (available fields: {$title}, {$url})',
'module_options' => 'Options',

'select_one' => 'Select one',
'export' => 'Export',
'serialized_datas' => 'PHP Serialized array',
'download' => 'Download',


'changelog' => '<ul>
<li>Version 0.0.1 - 29 September 2008. Initial Release.</li>
</ul>',
'help' => '<h3>What Does This Do?</h3>
<p>This module was generated by M&C Factory.</p>
<h2>Available actions</h2>

<h3>Default</h3>
<p>This action is used to generate the list of all items of the module.</p>
<h4>Params</h4>
<dl>
	<dt><em>orderby</em></dt>
	<dd>Comma-seperated list of orderby clauses. Eg. "column1, column2 DESC".</dd>
	<dt><em>limit</em></dt>
	<dd>Number of items to return.</dd>
	<dt><em>offset</em></dt>
	<dd>Start from this offset.</dd>
	<dt><em>random</em></dt>
	<dd>Randomize the order of the result.</dd>
	<dt><em>currentpage</em> (ModuleXtender)</dt>
	<dd>Boolean. Filter results on current page.</dd>
	<dt><em>pages</em> (ModuleXtender)</dt>
	<dd>Comma-seperated list of pages to filter on.</dd>
	<dt><em>options</em> (ModuleXtender)</dt>
	<dd>Comma-seperated list of options to filter on.</dd>
	<dt>date_field<dt>
	<dd>Allows you to specify the date_field to take in count for the digest</dd>
</dl>

<p>In the default template, you can get the params by calling {{literal}}{{{/literal}}${{$module->getModuleName()}}_params->params} where "->params" is an array of params.<p>

<h3>Detail</h3>
<p>This is the detail action for an item. The default template is automatically generated and you can restore it to understand how to use it?</p>
<h4>Params</h4>
<p>TODO</p>

<h3>Some actions that you can peform on the $item object</h3>
<p>For files (replace Fieldname by the name of your file field)</p>
<ul>
	<li><strong>$item->getFieldnameIcon()</strong>: Return an icon related to the file type.</li>
	<li><strong>$item->getFieldnameSize($readable = true)</strong>: Return the size of the file, human readable by default.</li>
	<li><strong>$item->getFieldnameExt()</strong>: Return the file type or extension.</li>
	<li><strong>$item->getFieldnameUrl()</strong>: Return the url. (useful in case of protected system).</li>
	<li><strong>$item->getFieldnameOriginalPictureUrl()</strong>: Return the original picture url.</li>
</ul>
<p>For modules (replace Fieldname by the name of your module field)</p>
<ul>
	<li><strong>$item->getFieldnameObject()</strong>: (Single value) this function exists and gives you the item object of the related module.</li>
	<li><strong>$item->getFieldnameItems()</strong>: (Multiple values) Same as precedent but returns an array of objects.</li>
</p>

<h3>Filters</h3>
<p>You can use filters to filter the lists or make a search tool.</p>
<p>Name is the name of the filter you want to create. Do not use special chars or space. Just numbers, letters and [_-] chars.</p>
<p>Field is the name of the field you want to filter.</p>
<p>Type is the type of sql query you want to perform.</p>
<p>Example:</p>
<ul>
	<li><strong>Search</strong>: {{literal}}{{{/literal}}{{$module->getModuleName()}} action="search"}</li> 
	<li><strong>Filter</strong>: {{literal}}{{{/literal}}{{$module->getModuleName()}} name_of_my_filter="value_for_filter"}</li> 
</ul>
<h3>Search</h3>
<p>You can use the search function to create a specific search engine for your module.</p>
<p>Example: {{literal}}{{{/literal}}{{$module->getModuleName()}} action="search"}</p>
<p>Params:</p>
<ul>
  <li><strong>filter_all</strong>: This param will create a text field to search on all the text fields of your module. You can create it empty (like filter_all="") otherwise it will come with a default value that you\'ve entered.</li>
  <li><strong>filter_title</strong>: Same as filter_all, except it only search on title</li>
  <li><strong>filters</strong>: list of filters you want to add. They have to exist in your module\'s filters. The list is separate by pipes (|) and the options of each modules are separated by ;. Example: filters="name=category;include_custom:Select a category|name=type"</li>
</ul>
<h3>url_for</h3>
<p>This action allows you to generate an url for a specific action (specified with the param "maction"). All the given params are transmitted to the action.</p>
<p>You can use the "clean_empty_values" param to remove empty values.</p>

<h3>link_to</h3>
<p>This action generate a link like url_for but pre formatted. You can specify the title with the param "title".</p>

<h3>iCal</h3>
<p>You can generate iCal(vCal) compatible xml with this module. Just call the function {{literal}}{{{/literal}}{{$module->getModuleName()}} action="ical" id="my_desired_id"} to generate the xml or the function {{literal}}{{{/literal}}{{$module->getModuleName()}} action="url_for" maction="ical" id="my_desired_id" showtemplate="false"} if you want the direct link to the ical xml.</p>

<h3>Calendar</h3>
<p>The calendar needs the following fields: start_date and end_date. Once those have been defined, you can build the calendar using the param \'calendar\'. It will create the following smarty vars: $calendar, $current_month, $next_month, $previous_month.</p>

<h3>RSS</h3>
<p>You can export your entries to RSS feeds. If you have mod_rewrite installed, just call the url "/{{$module->getModuleName()|lower}}/rss/xml". You can also call the action "rss" and pass some parameters like for the default action.</p>

<h3>Users content</h3>
<p>You can let users submit content via the module. For the form you can use the action "user_form". You can then modify the form template in the admin.</p>
<p>To let an user review his own submissions, you can use the default action and specify the param "show_user_items". This will allow a logged user to show his own submissions even the unpublished ones.</p>
<p>With this list you can also allow him to edit his own posts by using the action url_for with maction "user_form" and specifying item_id. It will only work with user\'s posts.</p>
<p>You can also check the permissions for publishing/editing, you can override the method "checkPermissions" in the M&C Factory custom logic. This function returns true or false and receive the $params as an array.</p>

<h3>Support</h3>
<p>As per the GPL, this software is provided as-is. Please read the text of the license for the full disclaimer.</p>
<h3>Copyright and License</h3>
<p>Copyright &copy; 2010, Jean-Christophe Cuvelier <a href="mailto:jcc@morris-chapman.com">&lt;jcc@morris-chapman.com&gt;</a> - Morris &amp; Chapman. All Rights Are Reserved.</p>
<p>This module has been released under the <a href="http://www.gnu.org/licenses/licenses.html#GPL">GNU Public License</a>. You must agree to this license before using the module.</p>'
);