<ul>
	<li>Version 0.4.2 - Compatibility fix for 1.11 series. This is NOT feature or bug release, just compatibility.</li>
	<li>Version 0.4.1 - March 2012. Last 0.x series release. Some UI improvement, bug fixes, nothing major.</li>
	<li>Version 0.4 - Jan 2011. Fixed Bugs #1822, #791, #3463, #3880, #5154, plus an additional fix for Bug #1204 and several other bugs. Added ability to filter by index fields.</li>
	<li>Version 0.3.2 - Aug 2010. Bug fixes.</li>
	<li>Version 0.3.1 - Jul 2010. Numerous Bug fixes. Bulk deletion of records. Character encoding options for Excel download. Option for UDT calls before rendering templates to allow for crazy customization. Integration into CMS search.</li>
	<li>Version 0.3 - Dec 2009. Bug fixes.</li>
	<li>Version 0.3b2 - Nov 2009. Bug fixes.</li>
	<li>Version 0.3b1 - Nov 2009. Rewrite, optimization, improvements.</li>
	<li>Version 0.2.3 - 30 May 2008. Alberto Benati\'s search code.</li>
	<li>Version 0.2.2 - 30 April 2008. Minor bug fix for parameters from tag.</li>
	<li>Version 0.2.1 - 28 April 2008. Bug fixes, column sorting, rewrite of Excel export.</li>
	<li>Version 0.2 - 15 Aug 2007. Upgraded to work with CMS Made Simple 1.1</li>
	<li>Version 0.1 - 8 July 2006. Initial Release.</li>
</ul>